### ISSUE TITLE
cross account / wallet id megaissue

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2494]
Mostly fallouts from: https://github.com/lbryio/lbry-sdk/issues/2264

- [x] utxo release should be cross account also
- [x] should status accept wallet id since we show locked/unlocked wallet there? If not, we need this info somewhere else, #2524 

- [x] ~account balance needs to take into account entire wallet~ moved to #2516

- [x] ~the below was removed from claim search/resolve calls, and only available locally. I thought these were supposed to be consistent? We don't use them, but https://github.com/lbryio/lbry-sdk/issues/2404 asks for it.~ tracked in #2404 

- [x] error updating/abanding streams/channels not in default wallet:
```
(lbry-venv) C:\Users\SoloDolo\lbry>lbrynet stream update --claim_id=bb40ffe2bcc0f10d31de6e58f16bf0ed4fa217b0 --preview
{
  "code": -32500,
  "data": [
    "Traceback (most recent call last):",
    "  File \"c:\\users\\solodolo\\lbry\\lbry\\lbry\\extras\\daemon\\Daemon.py\", line 584, in _process_rpc_call",
    "    result = await result",
    "  File \"c:\\users\\solodolo\\lbry\\lbry\\lbry\\extras\\daemon\\Daemon.py\", line 2853, in jsonrpc_stream_update",
    "    f\"Can't find the claim '{claim_id}' in account '{account.id}'.\"",
    "Exception: Can't find the claim 'bb40ffe2bcc0f10d31de6e58f16bf0ed4fa217b0' in account 'bVcVkepmh726dyhFFg3Jt4HP3ivEd6tkJX'.",
    ""
  ],
  "message": "Can't find the claim 'bb40ffe2bcc0f10d31de6e58f16bf0ed4fa217b0' in account 'bVcVkepmh726dyhFFg3Jt4HP3ivEd6tkJX'."
```

- [x] stream update returns this error, but publish command works as expected. Have also seen it on abandoning. I think it's related the above when not having the claims in default account + imported channel. 
```
2019-09-20 20:40:59,120 ERROR    lbry.extras.daemon.Daemon:590: error handling api request
Traceback (most recent call last):
  File "c:\users\solodolo\lbry\lbry\lbry\extras\daemon\Daemon.py", line 584, in _process_rpc_call
    result = await result
  File "c:\users\solodolo\lbry\lbry\lbry\extras\daemon\Daemon.py", line 2917, in jsonrpc_stream_update
    await tx.sign(funding_accounts)
  File "c:\users\solodolo\lbry\torba\torba\client\basetransaction.py", line 545, in sign
    private_key = await ledger.get_private_key_for_address(wallet, address)
  File "c:\users\solodolo\lbry\torba\torba\client\baseledger.py", line 193, in get_private_key_for_address
    return account.get_private_key(address_info['chain'], address_info['pubkey'].n)
  File "c:\users\solodolo\lbry\torba\torba\client\baseaccount.py", line 398, in get_private_key
    return self.address_managers[chain].get_private_key(index)
  File "c:\users\solodolo\lbry\torba\torba\client\baseaccount.py", line 112, in get_private_key
    return self.account.private_key.child(self.chain_number).child(index)
AttributeError: 'NoneType' object has no attribute 'child'
```

- [x] account send needs to take into account entire wallet

- [x] abandon / update apis need to support non-default accounts (see traceback above)

**Comment by eukreign** [comment]
fixed in https://github.com/lbryio/lbry-sdk/pull/2497
