### ISSUE TITLE
handling support and claim reorgs in leveldb

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-sdk#3143]
leveldb claimtrie
does not touch claim_search, removes usage of claims.db

- [x] fix blockchain.claimtrie.getclaimbyid, swap single claim searches (in tests) to use this.
- [x] handle abandon
- [x] store undo info
- [x] what to do about invalid signatures? no result vs return result and say signature is invalid. resolution: clients should validate signatures
- [x] handle same-block claims/supports
- [x] sync chain
- [x] PR the code
- [x] finish rebase
- [x] TAKEOVER/ACTIVATION HEIGHTS
- [x] wait till victor is done with claim_search because jack's branch drops claim search completely
- [x] confirm that app no longer uses trending fields from `resolve` and `claim_search` responses, since they have been dropped
- [x] handle takeovers from spent supports
- [x] feed ES claims from the block processor 
- [x] claim search tests pass
- [x] test takeover due to a dropped support in a reorg
- [x] test invalidated channel resolution for stream claims where the channel is dropped in a reorg
- [x] track repost counts in ES(45min)
- [x] make sure these make it back https://github.com/lbryio/lbry-sdk/blob/master/tests/unit/wallet/server/test_sqldb.py
- [x] test channel state changes
	- [x] invalidate prev claims for a channel when channel key changes
	- [x] check existing invalid claims in chan to see if any have become valid
	- [x] claim signature changes (adds sig, drops sig, signed by diff channel)
- [x] blocking censored content in `resolve`
  - [x] updates to plugins should let them know that update happened because censoring state changed
- [ ] write a summary of code changes in the PR to aid review
- [x] run on jack's local server so tom can do performance and correctness testing
  - check that as reorgs happen in the wild, this server stays correct

after PR is merged:
- [ ] ship a new snapshot (no more trending data)
- [ ] update all wallet servers
- [ ] consider doing #3131
- [x] have tests use claim_search and getclaimbyid, not just the latter

(later)

maybe redo this stuff inside hub instead of fetching from lbrycrd

- [x] activation delay (calc in #1031) - DONT LET THIS BOG YOU DOWN IF ITS NOT SIMPLE
- [x] add other height fields: active at, created
- [x] compare takeover heights against lbrycrd
- [x] compare effective amounts
- [x] compare controlling status
- [ ] replace block prefetcher with zmq client
- [ ] replace mempool polling with zmq client
- [ ] make zmq subscriber in Go (#3222)
- [ ] make plugin zmq notification sender (#3222)

(more later)

- [ ] replace usage of claim_hash with truncated form
- [ ] proofs
  - re-enable resolve proofs
  - include proofs in resolve proto response  
  - non-winning proofs (by claim_id)
- reduce boilerplate 
- wrap plyvel database (e.g. electrumx storage classes)

**Comment by lyoshenka** [comment]
- ~2.5h to sync
- next: finish claim sync

**Comment by lyoshenka** [comment]
api change: drop trending fields from `resolve` response. app doesnt use them

**Comment by lyoshenka** [comment]
estimate: 3 days left

**Comment by lyoshenka** [comment]
- get supports done
- run reorg tests
- wind chain back and forward a bunch

est: 2 days left

**Comment by lyoshenka** [comment]
jack says it feels 80% done

**Comment by lyoshenka** [comment]
outstanding:
- [ ] PR the code. write a summary of code changes in the PR to aid review
- [ ] fix short urls (easy)
- [ ] track repost counts (45min)
- [ ] blocking censored content
- [x] what to do about invalid signatures? no result vs return result and say signature is invalid. resolution: clients should validate signatures
- [ ] handle same-block claims/supports
- [ ] add a few more scenarios to reorg test (channel invalidation, dropping supports)
- [ ] wait till victor is done with claim_search because jack's branch drops claim search completely
- [ ] confirm that app no longer uses trending anywhere, since it has been dropped

gonna implement proofs in the future

after PR is merged:
- [ ] sync chain
- [ ] ship a new snapshot (no more trending data)
- [ ] update all wallet servers

**Comment by lyoshenka** [comment]
est: somewhere between "will finish today" and "unknown unknowns"

**Comment by lyoshenka** [comment]
found an unknown unknown

**Comment by lyoshenka** [comment]
est: tom can test against a build in the next 2 days

**Comment by lyoshenka** [comment]
- [ ] address tom's feedback
- [ ] fix performance issues
- [ ] run in docker
- [ ] ask devs in discord to try sdk.lbry.tech
- [ ] fix content blocking
- [ ] expose plyvel-lru cache size as env var
- [ ] make a snapshot
- [ ] deploy to spv19
