### ISSUE TITLE
Remove external SDK calls

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#3158]
- [x] ~~check if online (#3196)~~
- [x] ~~get external ip (#2142)~~
- [x] ~~exchange rate manager (related bug: #2158)~~
- [x] comments (#3408)
