### ISSUE TITLE
Cleanly represent in-progress livestreams

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#3180]
## todo
- [ ] add `--has-source` and `--has-no-source` flags to `claim_search` to select only claims that do/dont have a source
- [x] make sure that when you `publish`, the `source` is not required (maybe add flag to confirm you really intended not to have a source)
- [x] make sure `claim_update` can add a source
- [ ] notify @DispatchCommit when this is live on the cluster

## what
- need a clean way to represent a livestream that's in progress
- could just be hiding streams that don't have a source. but ideally the protobuf has a clean way of saying "this is a livestream"
- if hiding live streams, odysee needs a flag to include live streams in results

## why?
- want to tie comments to a claim
- want a url that can be shared (at least after stream has been uploaded, but maybe also during the stream)

## plan
- make a claim with no Source and optionally a future release date (if you know)
- add flag to claim_search to exclude streams without a source. app will start using this anytime it needs to exclude livestreams.
- after creator goes live, they (or we, for for them) will update this claim with the recorded livestream. this adds a source and takes it from livestream to normal claim.
- (nice to have) if you want a fixed url, repost the sourceless claim to another url (maybe `/live`). the repost will redirect to your next livestream claim, and comments will be attached correctly. once you've gone live and uploaded that stream, you make a new sourcecless claim and point your fixed repost to this new claim.

**Comment by kauffj** [comment]
@lyoshenka please update this

**Comment by seanyesmunt** [comment]
Why can't you use the url from this in-progress claim? Why do you need to repost?

**Comment by lyoshenka** [comment]
> Why can't you use the url from this in-progress claim? Why do you need to repost?

If you want a single fixed url to share. Let's say I go live every day at 3pm. I want to tell ppl "watch me at @grin/live". I don't want a new url every day.

Using the repost method, i can have `@grin/live` be a repost of that day's livestream claim. Since Odysee redirects users, they'll go to the correct claim (with related comments, etc)

**Comment by kauffj** [comment]
Any updates on this?

**Comment by lyoshenka** [comment]
victor should be done with search this week (assuming tonight's deploy to odysee cluster goes well). we can do this next
