### ISSUE TITLE
Track downloads or keys in local db to avoid paying multiple times for the same content

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#803]
(This was originally written by Grin but re-written/info added by @tzarebczan - in order to avoid confusion haha )

As a content consumer, I want to avoid paying multiple times for the same thing, or paying for something I do not receive, so I don't spend more credits than necessary.

As both a publisher and consumer of content via the LBRY app, I would like to be able to track what content purchase was associated with my wallet transactions and also what incoming payments are associated with my published items when they are downloaded.

Currently, when you download something that has a key fee, the only trace of it is the fact that it appears in your downloads directory. If you looked at the TX for the purchase, you can't tell which item it was for. Also, when someone purchases content you have set a key fee for, you can see the key payments coming into your wallet, but again, you can't tell which content it's for.

The transaction details (incoming / outgoing payments) would need to be stored in the transaction_list callback data.  This would require lbryum enhancements to https://github.com/lbryio/lbryum/blob/master/lbryum/commands.py which would tie the transaction information to the purchased content or incoming payment - issue opened here https://github.com/lbryio/lbryum/issues/176

The original intent here was to store purchases in a local db, but is that still required if they are stored in the transactions?

**Comment by tzarebczan** [comment]
@lyoshenka with all the transaction list enhancements we've had, this is a glaring hole right now. Would be great if we can start tracking this info or figure out a lbryum solution. Please bump up in priorty if you agree.

**Comment by lyoshenka** [comment]
steps:
- [ ] figure out db structure for storing payment info (connect claim_outpoint of payment to stream_hash of file)
- [ ] write migration
- [ ] add functions to save/retrieve payment info to Storage class
- [ ] add check for this in Downloader class
- [ ] add payment info to transaction_list and file_list
- [ ] figure out the correct model for storing deleted blobs. do you delete all the info in the db and just keep the sd blob on disk (so you have the key and don't need to get it again)? do you keep the db entries and just mark the blobs as deleted? something else?
- [ ] pr review

**Comment by tzarebczan** [comment]
@lyoshenka thinking about this again - do we really want to store this information in a db vs on the blockchain (i.e. some special type of support)?  If someone loses their LBRY database file, they wouldn't be able to reference back their incoming payments. 

What's the best solution going forward that would help with Proof of Purchase?

**Comment by tiger5226** [comment]
There is no restriction on where a Support is paid to in LBRYcrd. You could pay it to yourself, the claim_address, the fee_address or any address you want. Paying for content can easily be a support paid to the fee_address of the metadata. At that point the transaction is eternally linked to the claim_id.  So if someone loses their db files this can easily be parsed again. 

I think we can generalize `support` to be supporting claim functionality of LBRY. Any payment around the default behavior of LBRY like paying for claims, tipping claims, supporting claims, basically anything that is tied to a claim, like paying for channel membership even. Anything that can be associated with a claim. 

Until an unspent TxO is spent it will support the claim. Meaning until the publisher spends or who ever it is sent to. This should not be a problem because the claimtrie is under constant changes anyway and its not in the trie forever.

Again to answer the question, once it is a support an outpoint is permanently linked to a claimid making proof of purchase guaranteed. Now since metadata can be changed, someone could change the fee address, this wont matter because the claimid remains the same after an update.

**Comment by alyssaoc** [comment]
see also https://github.com/lbryio/lbrycrd/issues/184
@tzarebczan is checking with @jackrobison to see if this can be done without blockchain changes

**Comment by tzarebczan** [comment]
The first step of this (identifying the purchase) is currently being worked in https://github.com/lbryio/lbry/commit/6e2622448e6080f656d1bee595201b357efd50a4

**Comment by tiger5226** [comment]
Nice!

**Comment by alyssaoc** [comment]
@tiger5226 Which issues are still open?

**Comment by tiger5226** [comment]
@alyssaoc This one. Maybe you closed it accidentally.

**Comment by tzarebczan** [comment]
This is effectively being tracked in file list / lbrynet.sqlite so that a user can re-download/re-stream content they paid for. Maybe we can close this until we figure out a better long term solution?

**Comment by kauffj** [comment]
put :clap: the :clap: claim_id :clap: in :clap: the :clap: transaction

**Comment by tzarebczan** [comment]
The claim is in the transaction for new purchases. The desktop side (https://github.com/lbryio/lbry-desktop/issues/3183) needs some work now to make users aware on the UI.
